name: "Release"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}
            
      - name: Action | Semantic Version Release
        id: release
        # Adjust tag with desired version if applicable.
        uses: python-semantic-release/python-semantic-release@v9.15.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #git_committer_name: "github-actions"
          #git_committer_email: "actions@users.noreply.github.com"
          commit: false
          tag: false
          push: false
          build: false

      - name: Action | Update manifest.json and Commit   
        if: steps.release.outputs.released == 'true'
        run: |
          echo "Version: ${{steps.release.outputs.version}}"
          sed -i "s/\"version\": \".*\"/\"version\": \"${{steps.release.outputs.version}}\"/g" custom_components/frankenergy/manifest.json 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "chore: bumping version to ${{steps.release.outputs.version}}"
          git tag ${{ steps.release.outputs.tag }}
          git push --set-upstream origin main

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v9.15.2
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
