name: "Release"

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}
            
      - name: Action | Get Semantic Version Number
        id: version_check
        uses: python-semantic-release/python-semantic-release@v9.17.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: false
          tag: false
          push: false
          build: false

      - name: Action | Update manifest.json with new version 
        if: steps.version_check.outputs.released == 'true'
        run: |
          echo "Version: ${{steps.version_check.outputs.version}}"
          sed -i "s/\"version\": \".*\"/\"version\": \"${{steps.version_check.outputs.version}}\"/g" custom_components/frankenergy/manifest.json 
          git add -A

      - name: Action | Run Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.17.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: true
          tag: true
          push: true
          build: false

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v9.16.1
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
